import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import express from 'express';
import { createStore } from '../src/payment/store.js';
import { accountsFor, syncSource, command, view, deadlineCheck } from '../src/payment/domain.js';
import { createPaymentService } from '../src/payment/service.js';
const original=JSON.parse(readFileSync(new URL('../src/data/seed.json',import.meta.url)));
function fixture(){
 const source=structuredClone(original),store=createStore(':memory:');store.transaction(s=>syncSource(s,source));
 const c=store.read().contracts[0],accounts=accountsFor(source);
 const startup=accounts.find(a=>a.organisationId===c.startupId&&a.role==='startup'),department=accounts.find(a=>a.organisationId===c.departmentId&&a.role==='department'),finance=accounts.find(a=>a.organisationId===c.departmentId&&a.role==='finance'),reviewer=accounts.find(a=>a.role==='reviewer');
 const ids=store.read().milestones.filter(m=>m.state!=='imported_history').map(m=>m.id);
 const act=(actor,target,action,p={})=>store.transaction(s=>command(s,source,actor,target,action,{expectedVersion:s.milestones.find(m=>m.id===target)?.version,...p}));
 const configure=(extra={})=>act(department,c.id,'configure',{criteria:Object.fromEntries(ids.map(id=>[id,'Synthetic acceptance: execute agreed tests and provide reviewed results.'])),reviewDays:3,paymentDays:10,...extra});
 const submit=(mid=ids[0],extra={})=>act(startup,mid,'submit',{invoiceNumber:'INV-'+mid,invoiceDate:new Date().toISOString().slice(0,10),amountPaise:store.read().milestones.find(m=>m.id===mid).amountPaise,report:'SYNTHETIC REPORT: independent sample observations for '+mid,confirmed:true,...extra});
 const accept=(mid=ids[0])=>{const s=store.read(),m=s.milestones.find(m=>m.id===mid),sub=s.submissions.find(x=>x.id===m.submissionId);act(department,mid,'review',{decision:'accept',reason:'Reviewed invoice and all required test evidence.',evidenceHash:sub.evidenceHash,invoiceValid:true,criteriaMet:true,reuseReason:'Shared test report covers these separate deliverables.'});};
 return {source,store,c,startup,department,finance,reviewer,ids,act,configure,submit,accept};
}
test('imports seed relationships and preserves unverified Paid without counting it settled',()=>{const f=fixture();try{const d=view(f.store.read(),f.startup);assert.equal(d.contracts[0].id,'ct_seed_1');assert.equal(d.milestones.length,3);assert.equal(d.summary.paidThisQuarterPaise,0);assert.equal(d.summary.importedHistoryPaise,50000000);assert.equal(d.milestones[0].state,'imported_history');assert.throws(()=>f.submit(),/approve/);}finally{f.store.close();}});
test('contract terms are explicit and immutable; source changes block dependent actions',()=>{const f=fixture();try{f.configure();assert.throws(()=>f.configure(),/locked/);f.source.contracts[0].budgetAmount+=1;assert.throws(()=>f.submit(),/source contract changed/);}finally{f.store.close();}});
test('cross-organisation access and unknown roles are rejected',()=>{const f=fixture();try{f.configure();const other=accountsFor(f.source).find(a=>a.role==='startup'&&a.id!==f.startup.id);assert.equal(view(f.store.read(),other).contracts.length,0);assert.throws(()=>f.act(other,f.ids[0],'submit',{}),/not found/);assert.throws(()=>f.act({...f.startup,role:'admin'},f.ids[0],'submit',{}),/not found|not authorised/);assert.throws(()=>f.act(f.startup,f.ids[0],'approve',{}),/not authorised/);}finally{f.store.close();}});
test('amount tampering, repeated submission and duplicate invoices are blocked',()=>{const f=fixture();try{f.configure();assert.throws(()=>f.submit(f.ids[0],{amountPaise:1}),/amount/);f.submit(f.ids[0],{invoiceNumber:'DUP-001'});assert.throws(()=>f.submit(f.ids[0]),/another submission/);assert.throws(()=>f.submit(f.ids[1],{invoiceNumber:' dup-001 '}),/another milestone/);assert.equal(f.store.read().submissions.length,1);}finally{f.store.close();}});
test('corrections retain immutable evidence and original review deadline',()=>{const f=fixture();try{f.configure();f.submit();let s=f.store.read(),m=s.milestones.find(m=>m.id===f.ids[0]),first=m.reviewDueAt;const h=s.submissions[0].evidenceHash;f.act(f.department,m.id,'review',{decision:'correct',reason:'Provide missing sample logs and methodology.',evidenceHash:h});f.store.transaction(s=>{s.clockOffsetDays=4;deadlineCheck(s);});f.submit(f.ids[0],{report:'SYNTHETIC CORRECTED REPORT with detailed test logs.'});s=f.store.read();assert.equal(s.submissions.length,2);assert.equal(s.submissions[0].evidenceHash,h);assert.equal(s.milestones.find(m=>m.id===f.ids[0]).reviewDueAt,first);assert.equal(view(s,f.startup).summary.delayedReviews,1);assert.throws(()=>f.store.transaction(s=>{s.submissions[0].report='changed';}),/Immutable/);}finally{f.store.close();}});
test('stale versions and changed evidence cannot be approved; acceptance creates one obligation',()=>{const f=fixture();try{f.configure();f.submit();assert.throws(()=>f.act(f.department,f.ids[0],'review',{decision:'accept',reason:'Everything meets our acceptance requirements.',evidenceHash:'wrong',invoiceValid:true,criteriaMet:true}),/evidence version/);assert.throws(()=>f.act(f.department,f.ids[0],'review',{expectedVersion:0}),/record changed/);f.accept();assert.equal(f.store.read().payments.length,1);assert.throws(()=>f.accept(),/not awaiting/);const p=f.store.read().payments[0],m=f.store.read().milestones.find(m=>m.id===f.ids[0]);assert.equal(Date.parse(p.dueAt)-Date.parse(m.acceptedAt),10*86400000);}finally{f.store.close();}});
test('optional independent check blocks acceptance until reviewer passes the exact evidence',()=>{const f=fixture();try{f.configure({independent:{[f.ids[0]]:true}});f.submit();assert.throws(()=>f.accept(),/Independent/);let s=f.store.read();f.act(f.reviewer,f.ids[0],'independent-review',{decision:'pass',reason:'Independently repeated the sample tests and checked results.',noConflict:true,evidenceHash:s.submissions[0].evidenceHash});f.accept();assert.equal(f.store.read().payments.length,1);}finally{f.store.close();}});
test('funding holds retain obligation and original due date; reserved funds cannot be removed',()=>{const f=fixture();try{f.configure();f.submit();f.accept();const due=f.store.read().payments[0].dueAt;f.act(f.finance,f.c.id,'funding',{fundingPaise:50000000});f.act(f.finance,f.ids[0],'approve',{confirmed:true});let p=f.store.read().payments[0];assert.equal(p.fundingHold,true);assert.equal(p.status,'approval_pending');assert.equal(p.dueAt,due);f.act(f.finance,f.c.id,'funding',{fundingPaise:f.c.amountPaise});f.act(f.finance,f.ids[0],'approve',{confirmed:true});assert.throws(()=>f.act(f.finance,f.c.id,'funding',{fundingPaise:50000000}),/commitments/);}finally{f.store.close();}});
test('unknown outcomes block retries; reconciled failure allows one new attempt and success is terminal',()=>{const f=fixture();try{f.configure();f.submit();f.accept();f.act(f.finance,f.ids[0],'approve',{confirmed:true});assert.equal(f.store.read().payments[0].paidAt,null);f.act(f.finance,f.ids[0],'initiate');let a=f.store.read().attempts[0];f.act(f.finance,f.ids[0],'simulate',{attemptId:a.id,outcome:'timeout'});assert.throws(()=>f.act(f.finance,f.ids[0],'initiate'),/current state/);f.act(f.finance,f.ids[0],'simulate',{attemptId:a.id,outcome:'failure'});f.act(f.finance,f.ids[0],'initiate');a=f.store.read().attempts[1];f.act(f.finance,f.ids[0],'simulate',{attemptId:a.id,outcome:'success'});assert.equal(f.store.read().payments.length,1);assert.equal(f.store.read().payments[0].status,'paid');assert.throws(()=>f.act(f.finance,f.ids[0],'simulate',{attemptId:a.id,outcome:'failure'}),/unresolved/);}finally{f.store.close();}});
test('deadline checks include approved payments, run without page load and deduplicate alerts',()=>{const f=fixture();try{f.configure();f.submit();f.accept();f.act(f.finance,f.ids[0],'approve',{confirmed:true});f.store.transaction(s=>{s.clockOffsetDays=11;deadlineCheck(s);deadlineCheck(s);});const s=f.store.read();assert.equal(s.payments[0].status,'approved');assert.equal(s.notifications.filter(n=>n.type==='payment_overdue').length,1);assert.equal(view(s,f.startup).summary.overduePaise,s.payments[0].amountPaise);}finally{f.store.close();}});
test('independent disputes block approval, enforce assignment and can reopen rejected submissions',()=>{const f=fixture();try{f.configure();f.submit();const h=f.store.read().submissions[0].evidenceHash;f.act(f.department,f.ids[0],'review',{decision:'reject',reason:'Missing requested evidence for the field test.',evidenceHash:h});f.act(f.startup,f.ids[0],'dispute',{reason:'We dispute this rejection and request independent review.'});const d=f.store.read().disputes[0];assert.throws(()=>f.act(f.department,f.ids[0],'resolve-dispute',{}),/not authorised/);const assigned=accountsFor(f.source).find(a=>a.id===d.assignedTo);f.act(assigned,f.ids[0],'resolve-dispute',{disputeId:d.id,decision:'reopen',reason:'Allow the supplier to submit the omitted test evidence.',noConflict:true});assert.equal(f.store.read().milestones.find(m=>m.id===f.ids[0]).state,'correction_requested');assert.equal(f.store.read().disputes[0].status,'resolved');}finally{f.store.close();}});
test('HTTP sessions, idempotency, scheduler and persistence',async()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'vyavsay-v2-')),filename=path.join(dir,'payments.sqlite');let service,server,base;
 const boot=async()=>{service=createPaymentService({filename,readSource:()=>structuredClone(original),intervalMs:20});const app=express();app.use(express.json());app.use('/api/payments',service.router);server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api/payments`;};
 const close=async()=>{await new Promise(r=>server.close(r));service.close();};
 const req=async(path='',body,cookie,key=crypto.randomUUID())=>{const r=await fetch(base+path,{headers:{'Content-Type':'application/json','Idempotency-Key':key,...(cookie?{Cookie:cookie}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 try{
 await boot();assert.equal((await req()).status,401);assert.equal((await req('/session',{accountId:'fake'})).status,422);
 const accounts=(await req('/accounts')).data.accounts;const dept=accounts.find(a=>a.name==='Transport · Department reviewer');const cookie=(await req('/session',{accountId:dept.id})).cookie;
 const d=(await req('',null,cookie)).data,c=d.contracts[0],ms=d.milestones.filter(m=>m.state!=='imported_history');const body={criteria:Object.fromEntries(ms.map(m=>[m.id,'Demonstration tests and evidence reviewed against the contract.'])),reviewDays:3,paymentDays:10};
 const results=await Promise.all([req('/'+c.id+'/configure',body,cookie,'same-request'),req('/'+c.id+'/configure',body,cookie,'same-request')]);assert.deepEqual(results.map(r=>r.status),[200,200]);assert.equal(service.store.read().audit.filter(e=>e.action==='Demo contract terms approved').length,1);
 assert.equal((await req('/'+c.id+'/configure',{...body,paymentDays:11},cookie,'same-request')).status,409);
 const before=(await req('',null,cookie)).data;await close();await boot();const after=(await req('',null,cookie)).data;assert.equal(after.contracts[0].state,'approved_demo');assert.equal(after.contracts[0].approvedAt,before.contracts[0].approvedAt);
 }finally{if(server)await close();rmSync(dir,{recursive:true,force:true});}
});
