import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { accounts,packets } from '../src/validation/source.js';
import {sync,command,gate,view,integrity,append,fingerprint} from '../src/validation/domain.js';
import {createStore} from '../src/validation/store.js';
import {createValidationService} from '../src/validation/service.js';
const now='2026-09-10T00:00:00.000Z';
const seed=JSON.parse(fs.readFileSync(new URL('../src/data/seed.json',import.meta.url)));
function setup(risk='Medium',rng=n=>n===10000?9999:0){const store=createStore(':memory:');const s=store.read();store.close();const registry=accounts(seed),ps=packets(seed,{}),p=ps.find(p=>p.risk===risk&&p.synthetic);sync(s,[p],registry,now,rng);return {s,p,ps,registry,rng};}
const actor=(f,id)=>f.registry.find(a=>a.id===id);
const active=(f,kind='primary')=>f.s.assignments.find(a=>a.caseId===f.p.id&&a.kind===kind&&['assigned','reviewing'].includes(a.status));
function call(f,a,action,payload={}){command(f.s,[f.p],f.registry,a,f.p.id,action,payload,now,f.rng);sync(f.s,[f.p],f.registry,now,f.rng);}
function decision(f,result='approved',a=active(f),value=90){const user=actor(f,a.validatorId);call(f,user,'declare',{assignmentId:a.id,expectedVersion:a.version,noConflict:true});call(f,user,'decide',{assignmentId:a.id,expectedVersion:a.version,snapshotHash:f.s.rounds.at(-1).snapshotHash,result,reason:'Checked every source record independently.',evidence:'Synthetic trip logs checked against reference measurements.',checks:[{key:'accuracy',verifiedValue:value,verified:true,findings:'Recomputed the result from the source trip logs.'}]});}

test('seed gaps block review and imported Paid never substitutes for acceptance',()=>{const f=setup();const p=f.ps.find(p=>!p.synthetic);assert.equal(gate(f.s,p).eligible,false);assert.ok(gate(f.s,p).reasons.some(x=>x.includes('evaluator')));assert.ok(gate(f.s,p).reasons.some(x=>x.includes('imported Paid')));});
test('high-risk assignment excludes all involved people and uses different organisations',()=>{const f=setup('High');assert.equal(f.s.assignments.length,2);assert.equal(new Set(f.s.assignments.map(a=>a.organisationId)).size,2);const g=setup();g.s.rounds=[];g.s.assignments=[];g.s.audit=[];g.p.evaluatorIds=['validator:1','validator:2'];g.p.involvedIds=['validator:3'];sync(g.s,[g.p],g.registry,now,g.rng);assert.equal(active(g).validatorId,'validator:4');});
test('exhausted independent pool remains pending without relaxing conflicts',()=>{const f=setup();f.p.evaluatorIds=f.registry.filter(a=>a.role==='validator').map(a=>a.id);f.s.rounds=[];f.s.assignments=[];f.s.audit=[];sync(f.s,[f.p],f.registry,now,f.rng);assert.equal(f.s.assignments.length,0);assert.equal(gate(f.s,f.p).eligible,false);});
test('role and organisation abuse, missing declarations, and stale versions are rejected',()=>{const f=setup(),a=active(f);assert.throws(()=>call(f,actor(f,'department:demo'),'declare',{assignmentId:a.id,expectedVersion:1,noConflict:true}),/assigned validator/);assert.throws(()=>call(f,actor(f,'startup:st_tracknova'),'declare',{}),/not found/);assert.throws(()=>call(f,actor(f,a.validatorId),'decide',{assignmentId:a.id,expectedVersion:1}),/Declare independence/);assert.throws(()=>call(f,actor(f,a.validatorId),'declare',{assignmentId:a.id,expectedVersion:99,noConflict:true}),/changed/);});
test('approval requires mandatory targets and full evidence findings; decisions are single-use',()=>{const f=setup(),a=active(f);assert.throws(()=>decision(f,'approved',a,70),/mandatory target/);decision(f,'approved',a);assert.equal(gate(f.s,f.p).eligible,true);assert.throws(()=>decision(f,'approved',a),/closed/);assert.equal(f.s.decisions.length,1);assert.equal(integrity(f.s),true);});
test('high risk requires both blinded reviews; startup and peer identities stay restricted',()=>{const f=setup('High');decision(f);assert.equal(gate(f.s,f.p).eligible,false);const second=active(f),v=view(f.s,[f.p],f.registry,actor(f,second.validatorId));assert.equal(v.cases[0].decisions.length,0);assert.equal(v.cases[0].assignments.length,1);const startup=view(f.s,[f.p],f.registry,actor(f,'startup:demo'));assert.ok(!JSON.stringify(startup).includes('validator:'));decision(f);assert.equal(gate(f.s,f.p).eligible,true);});
test('random audit is sampled once, excludes the first reviewer, and blocks until complete',()=>{const f=setup('Medium',()=>0);decision(f);assert.equal(gate(f.s,f.p).status,'reaudit_pending');const a=active(f,'reaudit');assert.notEqual(a.validatorId,f.s.assignments[0].validatorId);const sampled=f.s.audit.filter(e=>e.eventType==='audit_sampled').length;sync(f.s,[f.p],f.registry,now,f.rng);assert.equal(f.s.audit.filter(e=>e.eventType==='audit_sampled').length,sampled);decision(f,'approved',a);assert.equal(gate(f.s,f.p).eligible,true);assert.equal(f.s.assignments.length,2);});
test('changed evidence and disputes invalidate eligibility; payment status alone does not',()=>{const f=setup();decision(f);f.p.milestones[0].payment.status='paid';assert.equal(gate(f.s,f.p).eligible,true);f.p.kpis[0].actual=80;assert.equal(gate(f.s,f.p).eligible,false);sync(f.s,[f.p],f.registry,now,f.rng);assert.equal(f.s.rounds[0].stale,true);assert.equal(f.s.rounds[0].snapshot.kpis[0].actual,90);const g=setup();decision(g);g.p.disputes.push({id:'d1',status:'open'});assert.equal(gate(g.s,g.p).eligible,false);});
test('corrections require revised evidence and a fresh round; rejection cannot be erased',()=>{const f=setup();decision(f,'corrections');assert.equal(gate(f.s,f.p).status,'corrections_required');const d=actor(f,'department:demo');assert.throws(()=>call(f,d,'resubmit',{reason:'Corrected the missing verification records.'}),/revised evidence/);f.p.revision=2;f.p.kpis[0].evidence.content+=' Revised';sync(f.s,[f.p],f.registry,now,f.rng);call(f,d,'resubmit',{reason:'Corrected the missing verification records.'});assert.equal(f.s.rounds.length,2);assert.equal(f.s.decisions[0].result,'corrections');const g=setup();decision(g,'rejected');g.p.revision=3;sync(g.s,[g.p],g.registry,now,g.rng);assert.throws(()=>call(g,actor(g,'department:demo'),'resubmit',{reason:'Trying to bypass an adverse decision.'}),/appeal/);});
test('appeals use a fresh independent adjudicator and remand never grants approval',()=>{const f=setup();decision(f,'rejected');call(f,actor(f,'startup:demo'),'appeal',{reason:'Please investigate an omitted evidence record.',evidence:'Additional synthetic observations for independent review.'});const a=active(f,'adjudication');assert.notEqual(a.validatorId,f.s.assignments[0].validatorId);call(f,actor(f,a.validatorId),'declare',{assignmentId:a.id,expectedVersion:a.version,noConflict:true});call(f,actor(f,a.validatorId),'decide',{assignmentId:a.id,expectedVersion:a.version,snapshotHash:f.s.rounds[0].snapshotHash,result:'remand',reason:'A fresh review is required for the omitted evidence.',evidence:'Reviewed the appeal and original observations.'});assert.equal(gate(f.s,f.p).status,'corrections_required');assert.equal(gate(f.s,f.p).eligible,false);});
test('recusal is persistent and deadline replacements require separate oversight approval',()=>{const f=setup(),a=active(f);call(f,actor(f,a.validatorId),'recuse',{assignmentId:a.id,expectedVersion:a.version,reason:'I have a prior employment relationship with this startup.'});assert.notEqual(active(f).validatorId,a.validatorId);const b=active(f);const later='2026-10-01T00:00:00.000Z';sync(f.s,[f.p],f.registry,later,f.rng);sync(f.s,[f.p],f.registry,later,f.rng);assert.equal(f.s.notifications.length,1);const payload={assignmentId:b.id,expectedVersion:b.version,reason:'Reviewer has not responded after multiple reminders.'};command(f.s,[f.p],f.registry,actor(f,'admin:1'),f.p.id,'propose-replacement',payload,later,f.rng);assert.throws(()=>command(f.s,[f.p],f.registry,actor(f,'admin:1'),f.p.id,'approve-replacement',payload,later,f.rng),/different oversight/);command(f.s,[f.p],f.registry,actor(f,'admin:2'),f.p.id,'approve-replacement',payload,later,f.rng);assert.equal(b.status,'replaced');});
test('tampered audit actor, sequence, decision and snapshot are detected',()=>{for(const field of ['actorId','eventType','createdAt','seq']){const f=setup();f.s.audit[0][field]='tampered';assert.equal(integrity(f.s),false);}const f=setup();decision(f);f.s.decisions[0].reason='tampered';assert.equal(integrity(f.s),false);const g=setup();g.s.rounds[0].snapshot.kpis[0].actual=100;assert.equal(integrity(g.s),false);});
test('persistent store forbids snapshot/decision changes and retains state after reopening',()=>{const folder=fs.mkdtempSync(path.join(os.tmpdir(),'validation-test-')),file=path.join(folder,'test.sqlite');const f=setup();let store=createStore(file);store.transaction(s=>Object.assign(s,f.s));assert.throws(()=>store.transaction(s=>{s.rounds[0].snapshot.kpis[0].actual=101;}),/overwritten/);store.close();store=createStore(file);assert.equal(store.read().rounds.length,1);assert.equal(integrity(store.read()),true);store.close();fs.rmSync(folder,{recursive:true,force:true});});
test('HTTP session, origin checks, idempotency conflict and isolated synthetic fixtures',async()=>{const service=createValidationService({filename:':memory:',readSource:()=>seed,readPayments:()=>({}),intervalMs:0,now:()=>now,rng:n=>n===10000?9999:0});const app=express();app.use(express.json());app.use('/api/validation',service.router);const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));try{const url=`http://127.0.0.1:${server.address().port}/api/validation`;assert.equal((await fetch(url)).status,401);assert.equal((await fetch(url+'/accounts',{headers:{Origin:'https://untrusted.invalid'}})).status,403);let response=await fetch(url+'/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:'validator:1'})});const cookie=response.headers.get('set-cookie').split(';')[0];let body=await(await fetch(url,{headers:{cookie}})).json();const c=body.cases.find(c=>c.packet.id==='demo:medium'),a=c.assignments[0];const headers={cookie,'Content-Type':'application/json','Idempotency-Key':'same-key-123'};const payload={assignmentId:a.id,expectedVersion:a.version,noConflict:true};const endpoint=url+'/demo%3Amedium/declare';assert.equal((await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(payload)})).status,200);assert.equal((await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(payload)})).status,200);assert.equal((await fetch(endpoint,{method:'POST',headers,body:JSON.stringify({...payload,noConflict:false})})).status,409);assert.equal(service.store.read().audit.filter(e=>e.eventType==='conflict_declaration').length,1);assert.equal(service.gateForDesign('pd_seed_1').eligible,false);}finally{await new Promise(resolve=>server.close(resolve));service.close();}});
